import type { PropsWithChildren, ReactElement } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { I18nProviderClient } from "#/lang/client";
import { cookies, headers } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: PropsWithChildren): ReactElement {
  const headerLanguages = headers().get("Accept-Language");
  const cookieLanguage = cookies().get("lang")?.value;

  const lang = cookieLanguage || headerLanguages?.substring(0, 2) || "en";

  return (
    <html>
      <body className={inter.className}>
        <I18nProviderClient locale={lang}>
          {children}
        </I18nProviderClient>
      </body>
    </html>
  );
}